/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.DB4O.DB4OUtil;
import business.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.userAccount.UserAccount;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek
 * @author Aelina
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private DB4OUtil dB4OUtil;
    private EcoSystem ecoSystem;

    public MainJFrame() {
        initComponents();
        this.setTitle("Community Service");
        loginPanel.setBackground(new Color(255, 255, 255, 150));
        //this.setLocationRelativeTo(null);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setSize(screenSize.width - 4, screenSize.height - 16);
        //this.validate();
        try {
            dB4OUtil = dB4OUtil.getInstance();
            ecoSystem = dB4OUtil.getEcoSystem();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        LoginAvatarJLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BackGroundJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setEnabled(false);
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Community Service");
        loginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 50));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Password");
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 135, 37));

        passwordField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 21)); // NOI18N
        passwordField.setBorder(null);
        loginPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 350, 50));

        loginBtn.setBackground(new java.awt.Color(102, 102, 102));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(null);
        loginBtn.setFocusPainted(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 150, 50));

        LoginAvatarJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginAvatarJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginAvatar.png"))); // NOI18N
        LoginAvatarJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginPanel.add(LoginAvatarJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 100));

        userNameTextField.setFont(new java.awt.Font("Microsoft Tai Le", 0, 23)); // NOI18N
        userNameTextField.setBorder(null);
        userNameTextField.setMinimumSize(new java.awt.Dimension(0, 25));
        userNameTextField.setPreferredSize(new java.awt.Dimension(0, 25));
        loginPanel.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 350, 50));
        userNameTextField.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Username");
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 135, 37));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Member Login");
        loginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 280, 50));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 510, 490));

        BackGroundJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginBG_Mac.jpg"))); // NOI18N
        BackGroundJLabel.setText("jLabel3");
        BackGroundJLabel.setPreferredSize(new java.awt.Dimension(1162, 520));
        getContentPane().add(BackGroundJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:

        String userName = userNameTextField.getText().trim();
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        UserAccount userAccount = ecoSystem.getUserAccountDirectory().authenticateUser(userName, password);
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        if (userAccount == null) {
            for (Network network : ecoSystem.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    if (userAccount == null) {
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                inEnterprise = enterprise;
                                inOrganization = organization;
                                break;
                            }
                        }

                    } else {
                        inEnterprise = enterprise;
                        break;
                    }
                    if (inOrganization != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
            }
        }

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials. Please enter valid Username and Password.", "Error", JOptionPane.ERROR_MESSAGE);
            userNameTextField.setText("");
            passwordField.setText("");
            return;
        } else {
            userNameTextField.setText("");
            passwordField.setText("");
            UserWorkAreaJFrame userWorkAreaJFrame=new UserWorkAreaJFrame(this, userAccount, inOrganization, inEnterprise, ecoSystem, dB4OUtil);
            userWorkAreaJFrame.setVisible(true);
            this.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundJLabel;
    private javax.swing.JLabel LoginAvatarJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
