/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.FoodBankOrganizationRole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.PantryOrganization;
import business.userAccount.UserAccount;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Abhishek
 */
public class FoodPantryStatsPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodPantryStatsPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PantryOrganization pantryOrganization;
    private EcoSystem ecoSystem;
    private HashMap<String, Integer> statsMap;

    public FoodPantryStatsPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pantryOrganization = (PantryOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        statsMap = pantryOrganization.getStatsMap();
        jDateChooser.setDate(new Date());
        jDateChooser.setMaxSelectableDate(new Date());
        JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateChooser.getDateEditor();
        editor.setEditable(false);
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) mealsServedTable.getModel();
        model.setRowCount(0);
        if (statsMap != null && !statsMap.isEmpty()) {
            Iterator<Entry<String, Integer>> iterator = statsMap.entrySet().iterator();
            while (iterator.hasNext()) {
                Map.Entry<String, Integer> next = (Map.Entry<String, Integer>) iterator.next();
                Object[] row = new Object[2];
                row[0] = next.getKey();
                row[1] = next.getValue();
                model.addRow(row);
            }
        }
    }

    private ArrayList sortDate(ArrayList<String> dateList) {
        Collections.sort(dateList, new Comparator<String>() {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

            @Override
            public int compare(String o1, String o2) {
                try {
                    return dateFormat.parse(o1).compareTo(dateFormat.parse(o2));
                } catch (ParseException ex) {
                    System.out.println("Date");
                }
                return -1;
            }
        });
        return dateList;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        servedjPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealsServedTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        numberjTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        statsjPanel = new javax.swing.JPanel();
        generateChartBtn = new javax.swing.JButton();
        chartDisplayPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        servedjPanel.setBackground(new java.awt.Color(255, 255, 255));

        mealsServedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Meals Served"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mealsServedTable);

        jLabel1.setText("Date*:");

        jLabel2.setText("Number of meals*:");

        numberjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberjTextFieldKeyTyped(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        refreshTestJButton.setBackground(new java.awt.Color(255, 255, 255));
        refreshTestJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        refreshTestJButton.setBorder(null);
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout servedjPanelLayout = new javax.swing.GroupLayout(servedjPanel);
        servedjPanel.setLayout(servedjPanelLayout);
        servedjPanelLayout.setHorizontalGroup(
            servedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servedjPanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(servedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servedjPanelLayout.createSequentialGroup()
                        .addGroup(servedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(servedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(numberjTextField)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(servedjPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshTestJButton)
                        .addGap(292, 292, 292))))
        );
        servedjPanelLayout.setVerticalGroup(
            servedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servedjPanelLayout.createSequentialGroup()
                .addGroup(servedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servedjPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(servedjPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(refreshTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(servedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(servedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Meals Served                                                                                            ", servedjPanel);

        statsjPanel.setBackground(new java.awt.Color(255, 255, 255));

        generateChartBtn.setText("Show Meals Statistics");
        generateChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateChartBtnActionPerformed(evt);
            }
        });

        chartDisplayPanel.setBackground(new java.awt.Color(255, 255, 255));
        chartDisplayPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        chartDisplayPanel.setLayout(new javax.swing.BoxLayout(chartDisplayPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout statsjPanelLayout = new javax.swing.GroupLayout(statsjPanel);
        statsjPanel.setLayout(statsjPanelLayout);
        statsjPanelLayout.setHorizontalGroup(
            statsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsjPanelLayout.createSequentialGroup()
                .addGroup(statsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statsjPanelLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(generateChartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statsjPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(chartDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        statsjPanelLayout.setVerticalGroup(
            statsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generateChartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Statistics                                                                                                     ", statsjPanel);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Meals Served / Statistics");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack)
                        .addGap(292, 292, 292)
                        .addComponent(jLabel3)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = dateFormat.format(jDateChooser.getDate()).toString().trim();
        if (date.equalsIgnoreCase("") || numberjTextField.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Please enter all fields", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int meals = Integer.parseInt(numberjTextField.getText().trim());
        statsMap.put(date, statsMap.containsKey(date) ? statsMap.get(date) + meals : meals);
        populateTable();
        numberjTextField.setText("");
    }//GEN-LAST:event_addButtonActionPerformed

    private void numberjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberjTextFieldKeyTyped
        // TODO add your handling code here:
        char enteredChar = evt.getKeyChar();
        if (!Character.isDigit(enteredChar) || (enteredChar == KeyEvent.VK_BACK_SPACE) || (enteredChar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_numberjTextFieldKeyTyped

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void generateChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateChartBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> keyList = new ArrayList<String>();
        if (statsMap != null && !statsMap.isEmpty()) {
            Set<String> keys = statsMap.keySet();
            for (String key : keys) {
                keyList.add(key);
            }
            Collections.sort(keyList, new Comparator<String>() {
                DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

                @Override
                public int compare(String o1, String o2) {
                    try {
                        return dateFormat.parse(o1).compareTo(dateFormat.parse(o2));
                    } catch (ParseException ex) {
                        System.out.println("Date");
                    }
                    return -1;
                }
            });
        }

        if (!keyList.isEmpty()) {
            DefaultCategoryDataset defaultCategoryDataset = new DefaultCategoryDataset();
            for (String mealDate : keyList) {
                defaultCategoryDataset.addValue(statsMap.get(mealDate), "Date", mealDate);
            }
            JFreeChart jFreeChart = ChartFactory.createBarChart3D("Pantry Meals Served", "Date", "Number of meals served per day", defaultCategoryDataset, PlotOrientation.VERTICAL, true, true, false);
            CategoryPlot categoryPlot = jFreeChart.getCategoryPlot();
            categoryPlot.setRangeGridlinePaint(Color.white);
            ChartPanel chartPanel = new ChartPanel(jFreeChart);
            chartPanel.setPreferredSize(new java.awt.Dimension(800, 500));
            chartDisplayPanel.removeAll();
            chartDisplayPanel.add(chartPanel);
            chartDisplayPanel.updateUI();
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, you currently do not have any data to display meal stats.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_generateChartBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel chartDisplayPanel;
    private javax.swing.JButton generateChartBtn;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable mealsServedTable;
    private javax.swing.JTextField numberjTextField;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JPanel servedjPanel;
    private javax.swing.JPanel statsjPanel;
    // End of variables declaration//GEN-END:variables
}
